//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooFinances
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodPriceTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodPriceTable()
        {
            this.AnimalTypeTables = new HashSet<AnimalTypeTable>();
        }
    
        public string Food_Type { get; set; }
        public decimal Food_Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalTypeTable> AnimalTypeTables { get; set; }
    }
}
