//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooFinances
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZooDatabaseEntities : DbContext
    {
        public ZooDatabaseEntities()
            : base("name=ZooDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnimalsTable> AnimalsTables { get; set; }
        public virtual DbSet<AnimalTypeTable> AnimalTypeTables { get; set; }
        public virtual DbSet<FoodPriceTable> FoodPriceTables { get; set; }
    }
}
